POWERLEVEL9K_MODE='nerdfont-complete'
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

#Load functions file if exists
if [ -f $HOME/.zshrc_fns ]; then
    . $HOME/.zshrc_fns
fi

#For tmux
#export TERM="xterm-256color"

#BASE CONFIG
POWERLEVEL9K_DISABLE_RPROMPT=false
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{075}%B❱%b%f "
#POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=()
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs dir)

#COLORS
POWERLEVEL9K_USER_DEFAULT_FOREGROUND="075"
POWERLEVEL9K_USER_DEFAULT_BACKGROUND="none"
POWERLEVEL9K_USER_ROOT_FOREGROUND="197"
POWERLEVEL9K_USER_ROOT_BACKGROUND="none"

POWERLEVEL9K_DIR_HOME_FOREGROUND="007"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="007"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_ETC_FOREGROUND="007"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="007"

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="none"
POWERLEVEL9K_DIR_HOME_BACKGROUND="none"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="none"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_ETC_BACKGROUND="none"

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="%F{075}%B❱%b%f"
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""

#GIT COLORS
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="077"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND="none"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="177"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="none"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='none'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='227'

#ICONS
#POWERLEVEL9K_HOME_ICON="\uf015"
POWERLEVEL9K_HOME_ICON=""
#POWERLEVEL9K_HOME_SUB_ICON="\uf07c"
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_HOME_SUB_ICON=""
POWERLEVEL9K_FOLDER_ICON=""
POWERLEVEL9K_VCS_GIT_ICON=""
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""

source ~/powerlevel10k/powerlevel10k.zsh-theme

